# Introduction 

## Intro 

## Aim of this book 

- The intended use of this text is to introduce the most useful types of statistical analysis including linear models and their generalized linear model (GLM) extensions 
- The approach is to learn by doing using real datasets relating to biological and environmental sciences 


## Changes in the second edition

## The R programming language for statistics and graphics 

## Scope 
- The focus is on linear model framework since this applies to biological sciences well
- GLMs are introduced for non-normal distributions 


## What is not covered
- Non-linear regression approaches, generalized additive models, non-parametric approaches 

## The approach 
- Most of the methods in this text belong to the 'classist frequentist statistics' 
- This approach has come under scrutiny due to its reliance on probability (p) values and lowered emphasis on effect sizes (estimates and intervals)
- The author is also pretty vocal about this criticism so he uses estimation-based approaches that focuses on estimates and confidence intervals where possible 
- He also uses *a priori* contrasts (comparisons that were planned in advance) and encourages avoidiing the inappropriate overuse of multiple testing and instead to implement a more thoughtful/planned approach 

## The new statistics? 
- This term basically refers to the criticisms mentioned in the last section and the recent focus on the use of confidence intervals and estimates
- This is combined with the use of the modern maximum likelihood-based analysis and methods for reproducible research 

## Getting started 
- There is an introduction to R section at the end of the text 
- The author dives right into things in the next chapter 



